/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "MetarankAPI": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "MetarankBillingTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "MetarankFrontend": {
      "type": "sst.aws.SvelteKit"
      "url": string
    }
    "MetarankUsageSnapshots": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "MetarankUsers": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "OPENAI_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PUBLIC_CLERK_PUBLISHABLE_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}