/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AIMApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "AIMUsageSnapshots": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "AIMUsers": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "BillingTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "MyWeb": {
      "type": "sst.aws.SvelteKit"
      "url": string
    }
    "OPENAI_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PUBLIC_CLERK_PUBLISHABLE_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PUBLIC_CLERK_PUBLISHABLE_KEY_PROD": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}