/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
<<<<<<< HEAD:apps/frontend/sst-env.d.ts
/* biome-ignore-all lint: auto-generated */
=======
>>>>>>> e06c53f123fdc33cfe00817d7f1e276d9a283973:packages/frontend/sst-env.d.ts

/// <reference path="../../sst-env.d.ts" />

import "sst"
export {}